### PR TITLE
Ensure language is always set

### PR DESCRIPTION
**Pull request by dandwal**
### What

Ensure that the locale is always set

### How to review

Check language should be and is set

### Who can review

Anyone except me

### CODE REVIEW

**Review by rav-pradhan — APPROVED** [review]

**Review by rav-pradhan — CHANGES_REQUESTED** [review]
Sorry - missed the tests weren't passing; looks to be an issue in the service_test file?

**Comment by dandwal** [comment]
> Sorry - missed the tests weren't passing; looks to be an issue in the service_test file?

Ah, @DavidSubiros this is the healthcheck test / service closing test that randomly fails that I was talking about before, concourse has captured an example of it failing.

**Comment by DavidSubiros** [comment]
> Ah, @DavidSubiros this is the healthcheck test / service closing test that randomly fails that I was talking about before, concourse has captured an example of it failing.

Maybe we should remove this test. It is testing that the graceful shutdown times out after the timeout has expired. For testing purposes I set a very small time out, but I imagine the context switching is too slow sometimes and the timeout is not detected. Maybe we should just remove this test, or increase the timeout into the 10s or 100s of milliseconds?

**Review by rav-pradhan — APPROVED** [review]
Off the back of the conversation, happy to approve this for now as the changes themselves are working and unrelated to the issue. In the interests of getting DAC related work over the line asap, too, the test case issue can be covered in a separate PR

**Pull request merged**
